insert  into constant(string_name, string_value, char_limit, url)values("VIRTUAL_TOUR_HEADER" , 'Placeholder', 250, "");
insert  into constant(string_name, string_value, char_limit, url)values("VIRTUAL_TOUR_MAIN_TEXT" , 'The card layouts can vary to support the types of content they contain', 250, "");
insert  into constant(string_name, string_value, char_limit, url)values("EXPERIENCE_HEADER" , 'Experience the Process', 250, "");
insert  into constant(string_name, string_value, char_limit, url)values("EXPERIENCE_MAIN_TEXT" , 'The card layouts can vary to support the types of content they contain', 250, "");
insert  into constant(string_name, string_value, char_limit, url)values("FAQ_HEADER" , 'Questions You Should Ask', 250, "");
insert  into constant(string_name, string_value, char_limit, url)values("FAQ_MAIN_TEXT" , 'The card layouts can vary to support the types of content they contain', 250, "");
insert  into constant(string_name, string_value, char_limit, url)values("SMALL_IMAGE_HEADER" , 'Sample Header', 250, "");
insert  into constant(string_name, string_value, char_limit, url)values("SMALL_IMAGE_TEXT" , 'Sample Text Medium', 250, "");
insert  into constant(string_name, string_value, char_limit, url)values("LONG_TEXT" , 'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry''s standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book.', 250, "");
insert  into constant(string_name, string_value, char_limit, url)values("VERT_NAV_HEADER" , 'Interactive Clinic', 250, "");
insert  into constant(string_name, string_value, char_limit, url)values("PLACEHOLDER_QUESTION" , 'Q: How does breast cancer effect breast milk production?', 250, "");
insert  into constant(string_name, string_value, char_limit, url)values("PLACEHOLDER_EXPANDED" , 'A: In the event of suggestive symptoms or when a screening test has given a positive result, various examinations should be performed to confirm or refute the diagnosis.', 250, "");
insert  into constant(string_name, string_value, char_limit, url)values("TEAM_SAMPLE_TEXT" , 'Dr. Song Hye Kyo', 250, "");
insert  into constant(string_name, string_value, char_limit, url)values("TEAM_SAMPLE_SUBTEXT" , 'Oncology Specialist', 250, "");
insert  into constant(string_name, string_value, char_limit, url)values("TEAM_SAMPLE_MAINTEXT" , 'Dr. Song gained her undergraduate degree in Biology from University of California, Irvine prior to attending University of Southern California''s Keck School of Medicine (2012).', 250, "");
insert  into constant(string_name, string_value, char_limit, url)values("HEADER_TITLE", 'Interactive Clinic', 250, "");
insert  into constant(string_name, string_value, char_limit, url)values("BUTTON_TEXT", 'Learn More', 250, "");
insert  into constant(string_name, string_value, char_limit, url)values("TREATMENT_TEXT", 'Treatment', 250, "");
insert  into constant(string_name, string_value, char_limit, url)values("BREAST_CANCER_TEXT", 'Breast Cancer', 250, "");
insert  into constant(string_name, string_value, char_limit, url)values("LANDING_PAGE_TITLE_A", 'Interactive', 250, "");
insert  into constant(string_name, string_value, char_limit, url)values("LANDING_PAGE_TITLE_B", 'Clinic', 250, "");
insert  into constant(string_name, string_value, char_limit, url)values("BREAST_CANCER_TEXT", 'Breast Cancer', 250, "");
insert  into constant(string_name, string_value, char_limit, url)values("TESTICULAR_CANCER_TEXT", 'Testicular Cancer', 250, "");
insert  into constant(string_name, string_value, char_limit, url)values("COLON_CANCER_TEXT", 'Colon Cancer', 250, "");
insert  into constant(string_name, string_value, char_limit, url)values("PATIENT_STORIES", 'Patient Stories', 250, "");
insert  into constant(string_name, string_value, char_limit, url)values("MEET_TEAM", 'Meet Your Team', 250, "");
insert  into constant(string_name, string_value, char_limit, url)values("ABOUT", 'About the Site', 250, "");
